CONTAINER AINODE_ZOIC
{
   NAME ainode_zoic;

   INCLUDE Obase;

   GROUP C4DAI_ZOIC_MAIN_GRP
   {
      DEFAULT 1;

      AIPARAM C4DAIP_ZOIC_SENSORWIDTH {}
      AIPARAM C4DAIP_ZOIC_SENSORHEIGHT {}
      AIPARAM C4DAIP_ZOIC_FOCALLENGTH {}
      AIPARAM C4DAIP_ZOIC_FSTOP {}
      AIPARAM C4DAIP_ZOIC_FOCALDISTANCE {}
      AIPARAM C4DAIP_ZOIC_USEIMAGE {}
      AIPARAM C4DAIP_ZOIC_BOKEHPATH {}
      AIPARAM C4DAIP_ZOIC_LENSMODEL {}
      AIPARAM C4DAIP_ZOIC_LENSDATAPATH {}
      AIPARAM C4DAIP_ZOIC_KOLBSAMPLINGLUT {}
      AIPARAM C4DAIP_ZOIC_USEDOF {}
      AIPARAM C4DAIP_ZOIC_OPTICALVIGNETTINGDISTANCE {}
      AIPARAM C4DAIP_ZOIC_OPTICALVIGNETTINGRADIUS {}
      AIPARAM C4DAIP_ZOIC_EXPOSURECONTROL {}
      AIPARAM C4DAIP_ZOIC_POSITION {}
      AIPARAM C4DAIP_ZOIC_LOOK_AT {}
      AIPARAM C4DAIP_ZOIC_UP {}
      AIPARAM C4DAIP_ZOIC_MATRIX {}
      AIPARAM C4DAIP_ZOIC_NEAR_CLIP {}
      AIPARAM C4DAIP_ZOIC_FAR_CLIP {}
      AIPARAM C4DAIP_ZOIC_SHUTTER_START {}
      AIPARAM C4DAIP_ZOIC_SHUTTER_END {}
      AIPARAM C4DAIP_ZOIC_SHUTTER_TYPE {}
      AIPARAM C4DAIP_ZOIC_SHUTTER_CURVE {}
      AIPARAM C4DAIP_ZOIC_ROLLING_SHUTTER {}
      AIPARAM C4DAIP_ZOIC_ROLLING_SHUTTER_DURATION {}
      AIPARAM C4DAIP_ZOIC_FILTERMAP {}
      AIPARAM C4DAIP_ZOIC_HANDEDNESS {}
      AIPARAM C4DAIP_ZOIC_TIME_SAMPLES {}
      AIPARAM C4DAIP_ZOIC_SCREEN_WINDOW_MIN {}
      AIPARAM C4DAIP_ZOIC_SCREEN_WINDOW_MAX {}
      AIPARAM C4DAIP_ZOIC_EXPOSURE {}
   }
}

