CONTAINER AITAG_ZOIC
{
   NAME aitag_zoic;

   GROUP C4DAI_ZOIC_MAIN_GRP
   {
      DEFAULT 1;

      GROUP C4DAI_ZOIC_GENERAL_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_ZOIC_SENSORWIDTH {}
         AIPARAM C4DAIP_ZOIC_SENSORHEIGHT {}
         AIPARAM C4DAIP_ZOIC_FOCALLENGTH {}
         AIPARAM C4DAIP_ZOIC_FSTOP {}
         AIPARAM C4DAIP_ZOIC_FOCALDISTANCE {}
         AIPARAM C4DAIP_ZOIC_LENSMODEL {}
      }

      GROUP C4DAI_ZOIC_IMAGEBOKEH_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_ZOIC_USEIMAGE {}
         AIPARAM C4DAIP_ZOIC_BOKEHPATH {}
      }

      GROUP C4DAI_ZOIC_RAYTRACED_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAI_ZOIC_RAYTRACED_GRP {}
         AIPARAM C4DAIP_ZOIC_LENSDATAPATH {}
         AIPARAM C4DAIP_ZOIC_KOLBSAMPLINGLUT {}
      }

      GROUP C4DAI_ZOIC_THINLENS_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_ZOIC_USEDOF {}
         AIPARAM C4DAIP_ZOIC_OPTICALVIGNETTINGDISTANCE {}
         AIPARAM C4DAIP_ZOIC_OPTICALVIGNETTINGRADIUS {}
      }

      GROUP C4DAI_ZOIC_EXTRA_GRP
      {
         DEFAULT 1;
         AIPARAM C4DAIP_ZOIC_EXPOSURECONTROL {}
      }
   }
}